### ISSUE TITLE
redgifs.com compatibility

### ISSUE THREAD

**Issue by 07416** [SpartanJ/ImgurViewer#22] opened 2021-07-05 14:21 UTC
It seems that the app can't parse redgifs.com anymore (supported domain).

**Comment by SpartanJ** [comment] 2021-07-18 01:51
You're right, I need to check the changes in their platform to see if I can still support it.

**Comment by SpartanJ** [comment] 2021-09-24 23:38
Fixed in current development branch: https://github.com/SpartanJ/ImgurViewer/commit/79e628a3e1b83a17e97aeadb37b8879ced709ff7 
Should be available for v2.2.2 release.

**Comment by youri--** [comment] 2022-10-22 20:23
Could it be this site has changed something to break compatibility again? It's not working for me.

As an aside, fyi: also not working in Hopwatch (Reddit on Android tv) and Slide for Reddit. Which leads me to believe there's a compat issue again due to the site changing something.

**Comment by SpartanJ** [comment] 2022-10-22 22:42
Can you please share a link that isn't working for you? ImgurViewer has some tests and the redgifs tests are passing. Thanks.

**Comment by youri--** [comment] 2022-10-23 09:03
Sure, just grabbed a random link (NSFW) from Reddit, it's not working:

<details>
  <summary>NSFW link</summary>

hXXps://www.redgifs.com/watch/beautifuluncomfortableegret

</details>

From this Reddit post:

<details>
  <summary>NSFW link</summary>

hXXps://reddit.com/r/u_kelsimonroe420/comments/y8snr1/my_first_redgifs_upload_2_years_ago_oc/

</details>

Error tooltip: "Sorry, video reproduction failed"

Another one from redgifs homepage 

<details>
  <summary>NSFW link</summary>

  hXXps://redgifs.com/watch/unwrittengreenazurevase

</details>

Error tooltip: "Couldn't resolve video url"

(Changed https to hXXps because it's NSFW and we're on github)

Opened 1st link via Slide for Reddit, long-press, "open externally", then choosing imgurviewer. Also tried long-press, Share, imgurviewer.
Opened 2nd link from homepage, in Firefox Focus, long-press, "open link in external app"

Device is OnePlus 6, Android 11, OxygenOS 11.1.2.2, stock

**Comment by SpartanJ** [comment] 2022-10-24 15:05
Oh, they deprecated their old API for the new videos. I'll have to take a look.

**Comment by youri--** [comment] 2022-10-27 14:38
Perhaps you've already seen this, but just in case you haven't. Found this on Reddit, could be useful

https://www.reddit.com/r/DataHoarder/comments/x67zfo/redgifs_api_now_blocked_from_hotlinking_anyone/

In the comments someone links to another app's repo who's also trying to figure out how to get it working again.

https://github.com/RipMeApp/ripme/issues/1994#issuecomment-1235137334

**Comment by SpartanJ** [comment] 2022-12-05 02:08
Thanks for the tips. I just pushed a fix. It'll be available in the next app release.

**Closed by SpartanJ** 2022-12-05 02:08 UTC
Labels: bug
